services:
  - docker

language: python

before_install:
- docker run -ti debian:buster /bin/bash
 

before_script:
  - mkdir -p build
  - cd build

script:
  - pwd
  - env
  - ls
  - uname -a
  - cat /etc/debian_version
