#
# use mksenv --distrib=<distrib> --pkgs=pkg1,pkg2,pkg3,... \
#     --split=[true,false] <thisfile.yml> [--docker,--script]
#

##############################################################################
wildcard: any

match:
  ubuntu: debian
##############################################################################
installer:
  any:
    fedora: dnf --setopt=deltarpm=false install -y
    debian: apt-get install -y --force-yes

updater:
  any:
    debian: apt-get update -y
    ubuntu-15.10: printf "deb http://ppa.launchpad.net/oli-huber/siconos/ubuntu wily main\ndeb-src http://ppa.launchpad.net/oli-huber/siconos/ubuntu wily main" >> /etc/apt/sources.list && apt-get update -y
    fedora:  dnf --setopt=deltarpm=false install -y dnf-plugins-core && dnf -y copr enable xhub/siconos-git

##############################################################################
env:
  clang:
    any:
      - CC=/usr/bin/clang
      - CXX=/usr/bin/clang++
      - OMPI_CC=/usr/bin/clang
      - OMPI_CXX=/usr/bin/clang++


##############################################################################
pkgs:

  build-base:
    any:
      - git-core
      - make
      - cmake
      - boost
      - gmp
      - swig
      - cppunit

  python-env:
    debian:
      - python
      - python-dev
      - python-lxml
      - python-pytest
      - python-scipy
      - python-matplotlib
    fedora:
      - python
      - python-devel
      - python-lxml
      - pytest
      - scipy
      - python-matplotlib

  python3-env:
    debian:
      - python3
      - python3-dev
      - libpython3-dev
      - python3-lxml
      - python3-pytest
      - python3-scipy
      - python3-matplotlib
    fedora:
      - python3
      - python3-devel
      - python3-lxml
      - python3-scipy
      - python3-pytest
      - python3-scipy
      - python3-matplotlib

  profiling:
    debian:
      - valgrind
      - python-dbg
    fedora:
      - valgrind
      - python-debuginfo

  cmake:
    ubuntu-12.04:
       - python-software-properties
       - python-matplotlib

  gnu-c++:
    debian: g++
    fedora: gcc-c++

  boost:
    debian: libboost-dev
    fedora: boost-devel

  gmp:
    debian: libgmp-dev
    fedora: gmp-devel

  cppunit:
    debian:
      - libcppunit-dev

    fedora: 
      - cppunit
      - cppunit-devel

  hdf5:
    fedora: hdf5-devel
    debian: libhdf5-dev

  h5py:
    fedora: h5py
    debian: python-h5py

  h5py3:
    any: python3-h5py

  openblas-lapacke:
    debian:
      - libopenblas-dev
      - liblapacke-dev
    fedora:
      - openblas-devel
      - lapack-devel

  atlas-lapack:
    debian:
      - libblas-dev
      - liblapack-dev
      - libatlas-base-dev
      - libatlas-dev

    fedora:
      - blas
      - blas-devel
      - atlas-devel

  oce:
    debian:
      - liboce-foundation-dev
      - liboce-modeling-dev
      - liboce-ocaf-dev
      - liboce-visualization-dev
      - oce-draw

    fedora:
      - OCE-devel

  mumps:
    debian-7.8:
      - libopenmpi-dev
      - openssh-client
      - libscalapack-mpi-dev
      - libscotchmetis-dev
      - libmumps-dev

    debian:
      - libopenmpi-dev
      - openssh-client
      - libscalapack-mpi-dev
      - libmetis-dev
      - libmumps-dev

    fedora:
      - ptscotch-openmpi 
      - ptscotch-openmpi-devel 
      - blacs-openmpi-devel
      - openmpi-devel
      - scalapack-openmpi
      - MUMPS-openmpi-devel
      - environment-modules

  bullet:
    debian:
      - libbullet-dev


# dummy target
  cfi:
    any:
      command: mkdir /tmp/clang && ln -s /usr/bin/ld.gold /tmp/clang/ld

  pythonocc:
    any:
      command: wget https://github.com/tpaviot/pythonocc-core/archive/0.16.3.tar.gz &&
               tar xvfz 0.16.3.tar.gz &&
               cd pythonocc-core-0.16.3 &&
               mkdir build &&
               cd build &&
               cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release &&
               make -j2 &&
               make install

  pythonocc-conda:
    any:
      command: wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh &&
               bash ./Miniconda-latest-Linux-x86_64.sh -b -p /opt/conda &&
               /opt/conda/bin/conda install numpy scipy lxml pytest matplotlib &&
               /opt/conda/bin/conda install -c https://conda.anaconda.org/dlr-sc pythonocc-core &&
               rm /opt/conda/lib/libgfortran.so*

               #echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh &&
               #echo 'export PATH=/opt/conda/bin:$PATH' >> $HOME/.profile &&

  pythonocc-conda-dep:
    debian:
      - libgl1-mesa-glx
      - libglu1-mesa
      - libsm6
      - libice6


# deps required for oce/pythonocc install, when oce/occ sources = git repos, last version.
  oce-pythonocc-deps:
    debian:
      - libgl1-mesa-glx
      - libglu1-mesa
      - libsm6
      - libice6


#  oce-pythonocc:
#    any:
#      command:
#git clone https://github.com/tpaviot/oce.git &&
#      	       git clone https://github.com/tpaviot/pythonocc-core.git &&
#               mkdir build &&
#               cd build &&
#	       mkdir oce-last pythonocc &&#
#	       cd oce-last &&
#               cmake ../../oce -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release &&
#               make -j 2 &&
#               make install &&
#	       cd ../pythonocc &&
#	       cmake ../../pythonocc-core -DCMAKE_BUILD_TYPE=Release &&
#	       make -j 2 &&
#	       make install &&
#	       cd &&
#	       python -c 'import OCC'