#
# use mksenv --distrib=<distrib> --pkgs=pkg1,pkg2,pkg3,... \
#     --split=[true,false] <thisfile.yml> [--docker,--script]
#

##############################################################################
wildcard: any

match:
  ubuntu: debian
##############################################################################
installer:
  any:
    fedora: dnf --setopt=deltarpm=false install -y
    debian: apt-get install -y --force-yes

updater:
  any:
    debian: apt-get update -y
    ubuntu-15.10: printf "deb http://ppa.launchpad.net/oli-huber/siconos/ubuntu wily main\ndeb-src http://ppa.launchpad.net/oli-huber/siconos/ubuntu wily main" >> /etc/apt/sources.list && apt-get update -y
    fedora:  dnf --setopt=deltarpm=false install -y dnf-plugins-core && dnf -y copr enable xhub/siconos-git

##############################################################################
pkgs:

  build-base:
    any:
      - git
      - make
      - cmake
      - boost
      - gmp
      - swig
      - cppunit

  python-env:
    debian:
      - python
      - python-dev
      - python-lxml
      - python-pytest
      - python-scipy
      - python-matplotlib
    fedora:
      - python
      - python-devel
      - python-lxml
      - pytest
      - scipy
      - python-matplotlib


# deps required for oce/pythonocc install, when oce/occ sources = git repos, last version.
  oce-pythonocc-deps:
    debian:
      - libgl1-mesa-glx
      - libglu1-mesa
      - libsm6
      - libice6


#  oce-pythonocc:
#    any:
#      command:
#git clone https://github.com/tpaviot/oce.git &&
#      	       git clone https://github.com/tpaviot/pythonocc-core.git &&
#               mkdir build &&
#               cd build &&
#	       mkdir oce-last pythonocc &&#
#	       cd oce-last &&
#               cmake ../../oce -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release &&
#               make -j 2 &&
#               make install &&
#	       cd ../pythonocc &&
#	       cmake ../../pythonocc-core -DCMAKE_BUILD_TYPE=Release &&
#	       make -j 2 &&
#	       make install &&
#	       cd &&
#	       python -c 'import OCC'